### ISSUE TITLE
Can't resolve 'vertx' in electron app

### ISSUE THREAD

**Issue by mhuggins** [stefanpenner/es6-promise#321] opened 2018-01-19 01:00 UTC
I'm trying to use `es6-promise` in an electron app, but there is a console warning with the following:

```
Module not found: Error: Can't resolve 'vertx' in '/Users/mhuggins/Development/neo/neon-wallet/node_modules/es6-promise/dist'
 @ ./node_modules/es6-promise/dist/es6-promise.js 140:16-26
 @ ./node_modules/es6-promisify/dist/promise.js
 @ ./node_modules/es6-promisify/dist/promisify.js
 ...
```

I see that the `package.json` for this package includes this entry:

```json
"browser": {
  "vertx": false
},
```

Is fixing this issue for electron as easy as adding this entry as well?

```json
"electron": {
  "vertx": false
},
```

In case it's relevant, the webpack `target` value is set to "electron".

**Comment by stefanpenner** [comment] 2018-01-19 01:06
> Is fixing this issue for electron as easy as adding this entry as well?

Not sure, can you share what code in electron is having trouble with this?

Maybe an example I can try out?

**Comment by stefanpenner** [comment] 2018-01-19 01:06
> In case it's relevant, the webpack target value is set to "electron".

Is this app built with webpack, if so it would be a duplicate of https://github.com/stefanpenner/es6-promise/issues/305

**Comment by mhuggins** [comment] 2018-01-19 02:28
Yes, it's built with webpack.  I wasn't clear if it falls under the same issue as that or not since it's an electron app.  This can be closed if it's the same.

**Comment by stefanpenner** [comment] 2018-01-19 02:32
Lets assume it does. I'm going to close.

I'm sick of this webpack issue, I'll try to find a reasonable solution shortly.

**Closed by stefanpenner** 2018-01-19 02:32 UTC

**Comment by quarterioningot** [comment] 2019-11-01 10:11
> Lets assume it does. I'm going to close.
> 
> I'm sick of this webpack issue, I'll try to find a reasonable solution shortly.

What was the solution?
