### ISSUE TITLE
Download links are broken in README

### ISSUE THREAD

**Issue by lostmsu** [stefanpenner/es6-promise#202] opened 2016-05-31 22:21 UTC
Subj

**Comment by HarryPehkonen** [comment] 2016-06-28 16:46
Going through the standard way to download content, Github gives this as the link for es6-promise.js:

https://github.com/stefanpenner/es6-promise/raw/master/dist/lib/es6-promise.js

There is no es6-promise.min.js in dist/lib at this time.

Pull-request #209

Please note that the above is not a duplicate of pull-request  #208.

**Comment by guidocalvano** [comment] 2016-07-06 10:07
Not only does it not work for master, but I can't find a past release where the link worked. I've checked about 5 versions.

**Closed** 2016-09-14 18:01 UTC
